package br.edu.utfpr.pb.trabalhofinal.view;

import br.edu.utfpr.pb.trabalhofinal.charts.ChartGen;
import br.edu.utfpr.pb.trabalhofinal.db.DatabaseConnection;
import br.edu.utfpr.pb.trabalhofinal.enums.EPermissao;
import br.edu.utfpr.pb.trabalhofinal.model.Usuario;
import br.edu.utfpr.pb.trabalhofinal.relatorio.Relatorios;
import br.edu.utfpr.pb.trabalhofinal.util.DataConverter;
import br.edu.utfpr.pb.trabalhofinal.util.UserSession;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class FrmPrincipal extends javax.swing.JFrame {

    private Timer timer;
    private String titulo = "Snow's Store ";
    private Usuario usuarioLogado;

    public FrmPrincipal() {
        initComponents();
        DatabaseConnection.getInstance().getConnection();

        timer = new Timer(1000, (ActionEvent e) -> {
            SimpleDateFormat sdf
                    = new SimpleDateFormat("HH:mm:ss");
            this.setTitle(titulo + sdf.format(new Date()));
        });

        timer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    FrmPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        UserSession.getInstance().setUsuarioLogado(usuario);
        UserSession sessao = UserSession.getInstance();

        menuFinanceiro.setEnabled(!sessao.temPermissao(EPermissao.VENDEDOR, EPermissao.FINANCEIRO));
        menuGerencial.setEnabled(!sessao.temPermissao(EPermissao.VENDEDOR));
        menuRelatorios.setEnabled(!sessao.temPermissao(EPermissao.VENDEDOR, EPermissao.FINANCEIRO));
        menuGrafs.setEnabled(!sessao.temPermissao(EPermissao.VENDEDOR, EPermissao.FINANCEIRO));

        timer = new Timer(1000, (ActionEvent e) -> {
            SimpleDateFormat sdf
                    = new SimpleDateFormat("HH:mm:ss");
            this.setTitle(titulo + sdf.format(new Date())
                    + " - Usuário: " + this.usuarioLogado.getNome());
        });

        timer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFinanceiro = new javax.swing.JMenu();
        menuContasPagar = new javax.swing.JMenuItem();
        menuContaReceber = new javax.swing.JMenuItem();
        menuGerencial = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuCidade = new javax.swing.JMenuItem();
        menuEstado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenuItem();
        menuOperacional = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        relComissaoUsers = new javax.swing.JMenuItem();
        menuRelVendas = new javax.swing.JMenuItem();
        menu2aVia = new javax.swing.JMenuItem();
        menuRelContasReceber = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuGrafs = new javax.swing.JMenu();
        menuGrafProd = new javax.swing.JMenuItem();
        menuGrafComissao = new javax.swing.JMenuItem();
        menuGrafPagamentos = new javax.swing.JMenuItem();
        menuGrafValorRecb = new javax.swing.JMenuItem();
        menuGrafInOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snow's Store");
        setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/financeiro.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro");

        menuContasPagar.setText("Contas a Pagar...");
        menuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasPagarActionPerformed(evt);
            }
        });
        menuFinanceiro.add(menuContasPagar);

        menuContaReceber.setText("Contas a Receber...");
        menuContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaReceberActionPerformed(evt);
            }
        });
        menuFinanceiro.add(menuContaReceber);

        jMenuBar1.add(menuFinanceiro);

        menuGerencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/cog.png"))); // NOI18N
        menuGerencial.setText("Gerencial");
        menuGerencial.add(jSeparator1);

        jMenu3.setText("Cadastros");

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/geo.png"))); // NOI18N
        jMenu5.setText("Locais");

        menuCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCidade.setText("Cidade...");
        menuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadeActionPerformed(evt);
            }
        });
        jMenu5.add(menuCidade);

        menuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuEstado.setText("Estado...");
        menuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoActionPerformed(evt);
            }
        });
        jMenu5.add(menuEstado);

        jMenu3.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/usuario.png"))); // NOI18N
        jMenu4.setText("Pessoas");

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuCliente.setText("Clientes...");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu4.add(menuCliente);

        menuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuFornecedor.setText("Fornecedor...");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu4.add(menuFornecedor);

        menuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuUsuario.setText("Usuários...");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuario);

        jMenu3.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/supply.png"))); // NOI18N
        jMenu6.setText("Produtos");

        menuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuProduto.setText("Produto...");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        jMenu6.add(menuProduto);

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuCategoria.setText("Categorias...");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu6.add(menuCategoria);

        jMenu3.add(jMenu6);

        menuGerencial.add(jMenu3);

        jMenuBar1.add(menuGerencial);

        menuOperacional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/cart.png"))); // NOI18N
        menuOperacional.setText("Operacional");

        menuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menuVendas.setText("Vendas...");
        menuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasActionPerformed(evt);
            }
        });
        menuOperacional.add(menuVendas);

        jMenuBar1.add(menuOperacional);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/relatorio.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");

        relComissaoUsers.setText("Comissao/Usuário");
        relComissaoUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relComissaoUsersActionPerformed(evt);
            }
        });
        menuRelatorios.add(relComissaoUsers);

        menuRelVendas.setText("Recbibo Venda");
        menuRelVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelVendas);

        menu2aVia.setText("2ª via recibo");
        menu2aVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2aViaActionPerformed(evt);
            }
        });
        menuRelatorios.add(menu2aVia);

        menuRelContasReceber.setText("Contas a Receber");
        menuRelContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelContasReceberActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelContasReceber);

        jMenuItem1.setText("Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem1);

        jMenuBar1.add(menuRelatorios);

        menuGrafs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/pb/finalOO2/image/chart.png"))); // NOI18N
        menuGrafs.setText("Gráficos");

        menuGrafProd.setText("Produtos/Mês");
        menuGrafProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrafProdActionPerformed(evt);
            }
        });
        menuGrafs.add(menuGrafProd);

        menuGrafComissao.setText("Comissão/Usuário");
        menuGrafComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrafComissaoActionPerformed(evt);
            }
        });
        menuGrafs.add(menuGrafComissao);

        menuGrafPagamentos.setText("Valores Pagos/Forma Pagto.");
        menuGrafPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrafPagamentosActionPerformed(evt);
            }
        });
        menuGrafs.add(menuGrafPagamentos);

        menuGrafValorRecb.setText("Valores Recebidos/Forma Pagto.");
        menuGrafValorRecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrafValorRecbActionPerformed(evt);
            }
        });
        menuGrafs.add(menuGrafValorRecb);

        menuGrafInOut.setText("Entradas x Saídas / Período");
        menuGrafInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGrafInOutActionPerformed(evt);
            }
        });
        menuGrafs.add(menuGrafInOut);

        jMenuBar1.add(menuGrafs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadeActionPerformed
        try {
            FrmCidadeLista frm = new FrmCidadeLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuCidadeActionPerformed

    private void menuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoActionPerformed
        try {
            FrmEstadoLista frm = new FrmEstadoLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuEstadoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        try {
            FrmClienteLista frm = new FrmClienteLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuClienteActionPerformed

    private void relComissaoUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relComissaoUsersActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");

        new Relatorios().comissaoUsuarios(DataConverter.getStringToData(dataInicial), DataConverter.getStringToData(dataFinal));
    }//GEN-LAST:event_relComissaoUsersActionPerformed

    private void menuRelVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelVendasActionPerformed
        String id = JOptionPane.showInputDialog(this, "Informe o ID da Venda");

        new Relatorios().reciboVenda(Long.parseLong(id));
    }//GEN-LAST:event_menuRelVendasActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        try {
            FrmUsuarioLista frm = new FrmUsuarioLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        try {
            FrmCategoriaLista frm = new FrmCategoriaLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        try {
            FrmProdutoLista frm = new FrmProdutoLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        try {
            FrmFornecedorLista frm = new FrmFornecedorLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void menuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasPagarActionPerformed
        try {
            FrmContaPagarLista frm = new FrmContaPagarLista(usuarioLogado);
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuContasPagarActionPerformed

    private void menuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasActionPerformed
        abreTelaVendas();
    }//GEN-LAST:event_menuVendasActionPerformed

    private void menuContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaReceberActionPerformed
        abreTelaContasReceber();
    }//GEN-LAST:event_menuContaReceberActionPerformed

    private void menuRelContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelContasReceberActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");
        new Relatorios().contasAReceber(DataConverter.getStringToData(dataInicial), DataConverter.getStringToData(dataFinal));
    }//GEN-LAST:event_menuRelContasReceberActionPerformed

    private void menu2aViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2aViaActionPerformed
        String id = JOptionPane.showInputDialog(this, "Informe o ID da Venda");
        new Relatorios().recibo2aVia(Long.parseLong(id));
    }//GEN-LAST:event_menu2aViaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");
        new Relatorios().vendas(DataConverter.getStringToData(dataInicial), DataConverter.getStringToData(dataFinal));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuGrafProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrafProdActionPerformed
        new ChartGen().produtosMes();
    }//GEN-LAST:event_menuGrafProdActionPerformed

    private void menuGrafComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrafComissaoActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");
        new ChartGen().comissaoUsuarios(DataConverter.getStringToData(dataInicial), DataConverter.getStringToData(dataFinal));
    }//GEN-LAST:event_menuGrafComissaoActionPerformed

    private void menuGrafPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrafPagamentosActionPerformed
        new ChartGen().valoresPagosByTipoRecebimento();
    }//GEN-LAST:event_menuGrafPagamentosActionPerformed

    private void menuGrafValorRecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrafValorRecbActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");

        new ChartGen().valoresRecebidosByTipoRecebimento(
                DataConverter.getStringToData(dataInicial),
                DataConverter.getStringToData(dataFinal)
        );
    }//GEN-LAST:event_menuGrafValorRecbActionPerformed

    private void menuGrafInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGrafInOutActionPerformed
        String dataInicial = JOptionPane.showInputDialog(this, "Informe a data inicial no formato dd/mm/aaaa");
        String dataFinal = JOptionPane.showInputDialog(this, "Informe a data final no formato dd/mm/aaaa");

        new ChartGen().entradasESaidas(
                DataConverter.getStringToData(dataInicial),
                DataConverter.getStringToData(dataFinal)
        );
    }//GEN-LAST:event_menuGrafInOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menu2aVia;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCidade;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuContaReceber;
    private javax.swing.JMenuItem menuContasPagar;
    private javax.swing.JMenuItem menuEstado;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenu menuGerencial;
    private javax.swing.JMenuItem menuGrafComissao;
    private javax.swing.JMenuItem menuGrafInOut;
    private javax.swing.JMenuItem menuGrafPagamentos;
    private javax.swing.JMenuItem menuGrafProd;
    private javax.swing.JMenuItem menuGrafValorRecb;
    private javax.swing.JMenu menuGrafs;
    private javax.swing.JMenu menuOperacional;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRelContasReceber;
    private javax.swing.JMenuItem menuRelVendas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenuItem menuVendas;
    private javax.swing.JMenuItem relComissaoUsers;
    // End of variables declaration//GEN-END:variables

    private void abreTelaVendas() {
        try {
            FrmVendaLista frm = new FrmVendaLista(usuarioLogado);
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void abreTelaContasReceber() {
        try {
            FrmContaReceberLista frm = new FrmContaReceberLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
