package br.edu.utfpr.pb.trabalhofinal.view;

import br.edu.utfpr.pb.trabalhofinal.db.DatabaseConnection;
import br.edu.utfpr.pb.trabalhofinal.model.Usuario;
import br.edu.utfpr.pb.trabalhofinal.relatorio.GerarRelatorio;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.view.JasperViewer;

public class FrmPrincipal extends javax.swing.JFrame {

    private Timer timer;
    private String titulo = "Snow's Store ";
    private Usuario usuarioLogado;

    public FrmPrincipal() {
        initComponents();
        DatabaseConnection.getInstance().getConnection();

        timer = new Timer(1000, (ActionEvent e) -> {
            SimpleDateFormat sdf
                    = new SimpleDateFormat("HH:mm:ss");
            this.setTitle(titulo + sdf.format(new Date()));
        });

        timer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    FrmPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        timer = new Timer(1000, (ActionEvent e) -> {
            SimpleDateFormat sdf
                    = new SimpleDateFormat("HH:mm:ss");
            this.setTitle(titulo + sdf.format(new Date())
                    + " - Usuário: " + this.usuarioLogado.getNome());
        });

        timer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuContasPagar = new javax.swing.JMenuItem();
        menuContaReceber = new javax.swing.JMenuItem();
        menuFonecedor = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCidade = new javax.swing.JMenuItem();
        menuEstado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuProdtCateg = new javax.swing.JMenuItem();
        menuRelVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu2.setText("Financeiro");

        menuContasPagar.setText("Contas a Pagar");
        menuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasPagarActionPerformed(evt);
            }
        });
        jMenu2.add(menuContasPagar);

        menuContaReceber.setText("Contas a Receber");
        menuContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaReceberActionPerformed(evt);
            }
        });
        jMenu2.add(menuContaReceber);

        jMenuBar1.add(jMenu2);

        menuFonecedor.setText("Gerencial");
        menuFonecedor.add(jSeparator1);

        jMenu3.setText("Cadastros");

        jMenu7.setText("Categorias");

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuCategoria.setText("Categorias");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu7.add(menuCategoria);

        jMenu3.add(jMenu7);

        jMenu5.setText("Locais");

        menuCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCidade.setText("Cidade");
        menuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadeActionPerformed(evt);
            }
        });
        jMenu5.add(menuCidade);

        menuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuEstado.setText("Estado");
        menuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoActionPerformed(evt);
            }
        });
        jMenu5.add(menuEstado);

        jMenu3.add(jMenu5);

        jMenu4.setText("Pessoas");

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuCliente.setText("Clientes");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu4.add(menuCliente);

        menuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu4.add(menuFornecedor);

        menuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuUsuario.setText("Usuários");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuario);

        jMenu3.add(jMenu4);

        jMenu6.setText("Produtos");

        menuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuProduto.setText("Produto");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        jMenu6.add(menuProduto);

        jMenu3.add(jMenu6);

        menuFonecedor.add(jMenu3);

        jMenuBar1.add(menuFonecedor);

        jMenu1.setText("Operacional");

        menuVendas.setText("Vendas");
        menuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVendas);

        jMenuBar1.add(jMenu1);

        menuRelatorios.setText("Relatórios");

        menuProdtCateg.setText("Produtos por Categoria");
        menuProdtCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdtCategActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuProdtCateg);

        menuRelVendas.setText("Vendas");
        menuRelVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelVendas);

        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadeActionPerformed
        try {
            FrmCidadeLista frm = new FrmCidadeLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuCidadeActionPerformed

    private void menuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoActionPerformed
        try {
            FrmEstadoLista frm = new FrmEstadoLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuEstadoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        try {
            FrmClienteLista frm = new FrmClienteLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2);

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuProdtCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdtCategActionPerformed
        String categoria = JOptionPane.showInputDialog(null, "Informe a categoria pra visualizar os produtos", JOptionPane.QUESTION_MESSAGE);

        GerarRelatorio relatorio = new GerarRelatorio();
        InputStream arquivo = this.getClass().getResourceAsStream("/reports/ativswing-produtosCategoria.jasper");
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("CATEGORIA", categoria);
        parametros.put("TITULO", "Produtos por Categoria");

        DatabaseConnection conn = DatabaseConnection.getInstance();
        JasperViewer viewer;
        try {
            viewer = relatorio.gerarRelatorio(
                    conn.getConnection(),
                    parametros,
                    arquivo);
            viewer.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao exibir relatório!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuProdtCategActionPerformed

    private void menuRelVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelVendasActionPerformed
        String clienteOuData = JOptionPane.showInputDialog(null, "Informe o nome do cliente ou a data desejada", JOptionPane.QUESTION_MESSAGE);

        for (char c : clienteOuData.toCharArray()) {

        }
        GerarRelatorio relatorio = new GerarRelatorio();
        InputStream arquivo = this.getClass().getResourceAsStream("/reports/ativswing-vendas-itens.jasper");
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("CLIENTE", clienteOuData);
        parametros.put("TITULO", "Relatório de Vendas");
        parametros.put("DATA", new Date());

        DatabaseConnection conn = DatabaseConnection.getInstance();
        JasperViewer viewer;
        try {
            viewer = relatorio.gerarRelatorio(
                    conn.getConnection(),
                    parametros,
                    arquivo);
            viewer.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao exibir relatório!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuRelVendasActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        try {
            FrmUsuarioLista frm = new FrmUsuarioLista();

            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();

            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );

            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        try {
            FrmCategoriaLista frm = new FrmCategoriaLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        try {
            FrmProdutoLista frm = new FrmProdutoLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        try {
            FrmFornecedorLista frm = new FrmFornecedorLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void menuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasPagarActionPerformed
        try {
            FrmContaPagarLista frm = new FrmContaPagarLista(usuarioLogado);
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuContasPagarActionPerformed

    private void menuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasActionPerformed
        try {
            FrmVendaLista frm = new FrmVendaLista(usuarioLogado);
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuVendasActionPerformed

    private void menuContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaReceberActionPerformed
        try {
            FrmContaReceberLista frm = new FrmContaReceberLista();
            Dimension size = jDesktopPane1.getSize();
            Dimension fSize = frm.getSize();
            frm.setLocation(
                    (size.width - fSize.width) / 2,
                    (size.height - fSize.height) / 2
            );
            jDesktopPane1.add(frm);
            frm.setVisible(true);
            frm.moveToFront();
            frm.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuContaReceberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCidade;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuContaReceber;
    private javax.swing.JMenuItem menuContasPagar;
    private javax.swing.JMenuItem menuEstado;
    private javax.swing.JMenu menuFonecedor;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenuItem menuProdtCateg;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRelVendas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenuItem menuVendas;
    // End of variables declaration//GEN-END:variables
}
